// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTSS8vMHGPnRGLCwrICnJC7YLOTRPmhBg',
    appId: '1:1024768647705:web:5707554652599e5e16c088',
    messagingSenderId: '1024768647705',
    projectId: 'iot-esp32-lis3dh',
    authDomain: 'iot-esp32-lis3dh.firebaseapp.com',
    databaseURL: 'https://iot-esp32-lis3dh-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-esp32-lis3dh.firebasestorage.app',
    measurementId: 'G-8GNNT1ENP6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBER2sqVotC69EmhVD2rRAFpFxDS4-rM5I',
    appId: '1:1024768647705:android:f0309acaa33176fb16c088',
    messagingSenderId: '1024768647705',
    projectId: 'iot-esp32-lis3dh',
    databaseURL: 'https://iot-esp32-lis3dh-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-esp32-lis3dh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwop7TeQEwK11AYDxXyOlCF8n8Ffw74nA',
    appId: '1:1024768647705:ios:2faf25f75723e20616c088',
    messagingSenderId: '1024768647705',
    projectId: 'iot-esp32-lis3dh',
    databaseURL: 'https://iot-esp32-lis3dh-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-esp32-lis3dh.firebasestorage.app',
    iosBundleId: 'com.example.appSilacak',
  );

}